FROM alpine:3.18.4

# Set metadata for the image
LABEL maintainer="Alexey <fmailp@yandex.ru>"
LABEL description="This is a Docker image for data migration."
LABEL version="1.0"
LABEL release-date="2023-09-30"

RUN apk --no-cache add postgresql-client
RUN echo "*:*:*:*:mypass" > ~/.pgpass
RUN chmod 600 ~/.pgpass

#CMD ["psql", "-h", "$DB_HOST", "-U", "$DB_USERNAME", "$DB_NAME", "-f", "your-migration-script.sql"]
#CMD ["sh", "-c", "psql --help "]
CMD ["sh", "-c", "psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -W$DB_PASSWORD -f migration_script.sql"]
CMD ["sh"]
